package com.example.spring_thymeleaf.enums;

public enum EmployeeDesignation{
    INTERN,
    GRADUATE_ENGINEER,
    JUNIOR_SOFTWARE_DEVELOPMENT_ENGINEER,
    SOFTWARE_DEVELOPMENT_ENGINEER,
    SENIOR_SOFTWARE_DEVELOPMENT_ENGINEER,
    EXPERT_SOFTWARE_DEVELOPMENT_ENGINEER,
    JUNIOR_SOFTWARE_DEVELOPMENT_ENGINEER_IN_TEST,
    SOFTWARE_DEVELOPMENT_ENGINEER_IN_TEST,
    SENIOR_DEVELOPMENT_ENGINEER_IN_TEST,
    EXPERT_DEVELOPMENT_ENGINEER_IN_TEST,
    TECHNICAL_DIRECTOR,
    ENGINEERING_MANAGER,
    HR_INTERN,
    HR_SPECIALIST,
    HR_MANAGER,
    HR_DIRECTOR,
    OFFICE_ASSISTANT,
    OFFICE_MANAGER,
    OPERATIONS_MANAGER,
    DIRECTOR_OF_ADMINISTRATION,
    CEO;
        }